# -*- coding: utf-8 -*-
"""app_M-Pajak.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZDXzUL7r8oXlVB5UVpIQpDvkRZxAV2C9
"""

!pip install streamlit

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# Load data
@st.cache_data
def load_data():
    # Load the updated CSV file that includes the 'topik_label' column
    return pd.read_csv("hasil_topik.csv")

df = load_data()

# Mapping topik
topic_titles = {
    0: 'Kesulitan Melapor & Bayar Pajak',
    1: 'Masalah Kode Verifikasi & OTP',
    2: 'Ulasan Campuran: Puas & Keluhan Error',
    3: 'Gagal Akses atau Daftar Akun',
    4: 'Masalah Pembuatan & Validasi NPWP'
}
topic_map = {v: k for k, v in topic_titles.items()}

# ==================
# Layout dashboard
# ==================
st.title("Dashboard Pemetaan Topik Masalah DJP Online")

# Pie chart distribusi
st.header("Distribusi Topik Ulasan")
fig1 = plt.figure(figsize=(7,7))
df['topik_label'].value_counts().plot.pie(autopct='%1.1f%%')
plt.ylabel('')
st.pyplot(fig1)

# Wordcloud dinamis
st.header("Wordcloud Topik")
topik_options = df['topik_label'].unique().tolist()
pilih_topik = st.selectbox("Pilih Topik:", topik_options)

st.write(f"✅ Kamu memilih topik: **{pilih_topik}**")

# Cari nomor topik sesuai pilihan
topik_no = topic_map.get(pilih_topik)

if topik_no is not None:
    topik_no += 1  # File wordcloud_topik_X.png pakai nomor mulai dari 1
    try:
        st.image(f"wordcloud_topik_{topik_no}.png", caption=f"Wordcloud: {pilih_topik}")
    except FileNotFoundError:
        st.warning(f"Wordcloud image for topic '{pilih_topik}' not found.")
else:
    st.warning("Topik tidak dikenali. Silakan pilih topik yang tersedia.")

# Contoh ulasan
st.header("Contoh Ulasan dari Topik Ini")
topic_subset = df[df['topik_label'] == pilih_topik]['clean_content']
sample_size = min(5, len(topic_subset))
if sample_size > 0:
    sample = topic_subset.sample(sample_size, random_state=42).tolist()
    for i, s in enumerate(sample, 1):
        st.write(f"{i}. {s}")
else:
    st.info("No reviews available for this topic.")